apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: 345nani/rest-api:latest  # This will be dynamically updated
          ports:
            - containerPort: 8080
